apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: ravis2470/jenkins:1
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-pv
          mountPath: "/mnt/jenkins"
        - mountPath: /var/run/docker.sock
          name: docker-sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name : jenkins-pv
        persistentVolumeClaim:
          claimName: jenkins-pvc
